Fix pathing issues

diff --git a/.github/actions/update-version/action.yml b/.github/actions/update-version/action.yml
--- a/.github/actions/update-version/action.yml
+++ b/.github/actions/update-version/action.yml
@@ -8,17 +8,16 @@ runs:
   steps:
     - name: Increment patch version and update hash
       run: |
-        VERSION_FILE="${{ env.SDK_PATH }}/lib/ragie_ruby_sdk/version.rb"
+        VERSION_FILE="./${{ env.SDK_PATH }}/lib/ragie_ruby_sdk/version.rb"
         if [ -f "$VERSION_FILE" ]; then
           CURRENT_VERSION=$(grep -oE "[0-9]+\.[0-9]+\.[0-9]+" "$VERSION_FILE")
           IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
           PATCH=$((PATCH + 1))
           NEW_VERSION="$MAJOR.$MINOR.$PATCH"
-          sed -i "s/VERSION = .*/VERSION = '$NEW_VERSION'/" "$VERSION_FILE"
+          sudo sed -i "s/VERSION = .*/VERSION = '$NEW_VERSION'/" "$VERSION_FILE"
         else
-          NEW_VERSION="0.0.1"
-          mkdir -p "$(dirname "$VERSION_FILE")"
-          echo "module RagieRubySdk; VERSION = '$NEW_VERSION'; end" > "$VERSION_FILE"
+          echo "Version file not found: $VERSION_FILE"
+          exit 1
         fi
         echo "${{ inputs.sdk_hash }}" > .last_sdk_hash
       shell: bash
